[package]
name = "boilermaker_api"
version = "0.1.0"
edition = "2021"

[dependencies]
# External
dioxus = { workspace = true, features = ["fullstack"] }
# Internal
boilermaker_core = { workspace = true }
