[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
indoc = { workspace = true }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server"]
